/**
* todo
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param state 
 * @param message 
 */
data class ResultState (
    val state: ResultState.State? = null,
    val message: kotlin.String? = null
) 
{
    /**
    * 
    * Values: oK,fail
    */
    enum class State(val value: kotlin.String){
        oK("OK"),
        fail("Fail");
    }
}

