openapi: 3.0.0
info:
  title: todo
  version: '1.0'
servers:
  - url: 'http://localhost:4010'
paths:
  /delete_todo_task:
    delete:
      summary: delete_todo_task
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultState'
      operationId: delete-todo-todo_task
      parameters:
        - schema:
            type: string
          example: '1'
          in: query
          name: id
          required: true
    parameters: []
  /todo_list:
    get:
      summary: todo_list
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/TodoTask'
                required:
                  - todos
      operationId: get-todo_list
  /get_todo_task:
    get:
      summary: get_todo_task
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoTask'
      operationId: get-get_todo_task
      parameters:
        - schema:
            type: string
          example: '1'
          in: query
          name: id
          required: true
      description: ''
    parameters: []
  /create_todo_task:
    post:
      summary: create_todo_task
      tags:
        - todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultState'
      operationId: post-create_todo_task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todoTask:
                  $ref: '#/components/schemas/TodoTask'
              required:
                - todoTask
            examples:
              example-1:
                value:
                  todoTask:
                    id: '1'
                    label: todo sample
                    created_at: '2020/05/03 22:00:05'
                    finished: false
      parameters: []
      description: ''
components:
  schemas:
    TodoTask:
      title: TodoTask
      type: object
      x-examples: {}
      x-tags:
        - todo
      properties:
        id:
          type: string
        label:
          type: string
        created_at:
          type: string
        finished:
          type: boolean
        author:
          type: string
      required:
        - id
        - label
        - created_at
        - finished
    ResultState:
      title: ResultState
      type: object
      properties:
        state:
          type: string
          enum:
            - OK
            - Fail
          example: OK
        message:
          type: string
      x-tags:
        - todo
    TodoTasks:
      title: TodoTasks
      type: object
      properties:
        todos:
          $ref: '#/components/schemas/TodoTask'
