/* tslint:disable */
/* eslint-disable */
/**
 * todo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TodoTask,
    TodoTaskFromJSON,
    TodoTaskFromJSONTyped,
    TodoTaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface TodoTasks
 */
export interface TodoTasks {
    /**
     * 
     * @type {TodoTask}
     * @memberof TodoTasks
     */
    todos?: TodoTask;
}

export function TodoTasksFromJSON(json: any): TodoTasks {
    return TodoTasksFromJSONTyped(json, false);
}

export function TodoTasksFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoTasks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'todos': !exists(json, 'todos') ? undefined : TodoTaskFromJSON(json['todos']),
    };
}

export function TodoTasksToJSON(value?: TodoTasks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'todos': TodoTaskToJSON(value.todos),
    };
}


